name: 功能请求
description: 提出一项新的功能。
title: （将此栏【替换】为你的标题）
labels: ["新功能", "未查看"]
type: Feature
body:
  - type: markdown
    attributes:
      value: |
        感谢您贡献您的想法。请在上面的文本框⬆️起一个能够清晰概括此功能的标题，便于开发者了解您的想法。
        
        > [!important]
        > 重要：如果您想要提出 **多项功能**，请为每一个功能开一个单独的 issue。
        >
        > 由于开发者时间精力有限，加上已经积压了大量的功能请求，提交的功能请求可能需要比较久的时间才能实现。
  - type: checkboxes
    id: checklist
    attributes:
      label: 检查清单
      description: 在开始反馈这个问题之前，请先检查：
      options:
        - label: 我已将本应用更新到最新测试版 ![最新的版本号](https://img.shields.io/github/v/release/Round-Studio/Round.NET.AvaloniaApp.MinecraftLauncher?style=flat-square&label=)，并看过[最新提交](https://github.com/Round-Studio/Round.NET.AvaloniaApp.MinecraftLauncher/commits/master/)，确认我想要的功能还没有实现。
          required: true
        - label: 我已在 [Issues](https://github.com/Round-Studio/Round.NET.AvaloniaApp.MinecraftLauncher/issues?q=label%3A新功能) 和 [RMCL 文档](https://gh.roundstudio.top)中检索，确认我想要的功能未被提交过。
          required: true
        - label: 我认为我想要的功能是用户广泛需要的，插件不能替代的，且没有超出 RMCL 作为**我的世界启动器**的开发目标，而非添加与我的世界启动无关的内容。（您可以学习[编写插件](https://gh.roundstudio.top)来实现特殊的需求）。
          required: true
        - label: 我已知晓由于开发者时间精力有限，加上已经积压了大量的功能请求，我提交的功能请求可能需要比较久的时间才能实现。
          required: true
  - type: textarea
    id: back
    attributes:
      label: 背景与动机
      description: 添加此功能的理由。
    validations:
      required: true
  - type: textarea
    id: req
    attributes:
      label: 想要实现或优化的功能
      description: 详细地描述一下你想要的功能，描述的越具体，采纳的可能性越高。
    validations:
      required: true
  - type: checkboxes
    id: revision
    attributes:
      label: 最后一步
      description: 回顾您的回答
      options:
        - label: 我认为上述的描述已经足以详细，以便开发人员理解您想要的功能。如果我的 issue 没有按照上述的要求填写，可能会被无条件关闭。
          required: true
